---
- hosts: raspicams
  vars:
      # syslog server receiving logs from raspicams
      syslog_host: 192.168.1.1
      syslog_port: 51400
  tasks:
      - copy:
          src: config/etc/
          dest: /etc/
      - copy:
          src: config/usr/local/bin/
          dest: /usr/local/bin/
          owner: root
          group: staff
          mode: u=rwx,g=rx,o=rx
      - copy:
          src: config/usr/local/sbin/
          dest: /usr/local/sbin/
          owner: root
          group: staff
          mode: u=rwx,g=rx,o=rx
      - template:
          src: template/etc/rsyslog.d/tcp.conf
          dest: /etc/rsyslog.d/tcp.conf
      - package:
          name: motion
          state: present
      - package:
          name: tree
          state: present
      - package:
          name: vim
          state: present
      - package:
          name: i2c-tools
          state: present
      - file:
          src: /usr/local/sbin/remove-old-records
          dest: /etc/cron.daily/remove-old-records
          state: link
      - cron:
          name: 'check motion'
          job: 'systemctl status motion || systemctl restart motion'
      #- user:
          #name: motion
          #home: /home/motion
          #move_home: yes
      #- group:
          #name: motion

      #
      # Extending life of sd card
      #

      # external drive to save videos
      - mount:
          name: /home/motion
          fstype: vfat
          src: /dev/sda1
          opts: defaults,uid=motion,gid=motion
          state: present
          passno: 1
      - mount:
          name: /tmp
          fstype: tmpfs
          src: tmpfs
          opts: defaults,noatime,nosuid,size=100m
          state: present
      - mount:
          name: /var/tmp
          fstype: tmpfs
          src: tmpfs
          opts: defaults,noatime,nosuid,size=30m
          state: present
      - mount:
          name: /var/log
          fstype: tmpfs
          src: tmpfs
          opts: defaults,noatime,nosuid,mode=0755,size=100m
          state: present
      - mount:
          name: /run
          fstype: tmpfs
          src: tmpfs
          opts: defaults,noatime,nosuid,mode=0755,size=100m
          state: present
