#!/usr/bin/env bash

pin="24"

echo "${pin}" > /sys/class/gpio/export
sleep 1
echo "out" > /sys/class/gpio/gpio${pin}/direction

echo "1" > /sys/class/gpio/gpio${pin}/value
sleep 0.1
echo "0" > /sys/class/gpio/gpio${pin}/value

echo "${pin}" > /sys/class/gpio/unexport

